Make some tweaks
- $PGDIFF_CONNECTION_STRING now defines the connection info that the script will use
- Swap `columns` for `awk` because it handles long lines
- Add `--no-pager` to `git diff` so that `script` doesn't choke

diff --git a/pgdiff b/pgdiff
--- a/pgdiff
+++ b/pgdiff
@@ -1,15 +1,21 @@
 #!/bin/bash
 
-schema="public"
-db="$1"
-id="$2"
+id="$1"
 
 if [ "$1" = "-d" ]; then
     rm -rf "/var/tmp/pgdiff"
-    exit 0;
+    exit 0
 fi
 
-tables=$(psql -t -c "select tablename from pg_tables where schemaname not in ('information_schema', 'pg_catalog')" $db | awk 'NF {print($1)}')
+pg_isready -d "$PGDIFF_CONNECTION_STRING" > /dev/null
+if [[ $? -ne 0 ]]; then
+    echo "PGDIFF_CONNECTION_STRING is not set, or unable to connect to database (eg. 'postgresql://user:password@host:port/db_name')";
+    exit 1
+fi
+
+db=${PGDIFF_CONNECTION_STRING##*/}
+
+tables=$(psql $PGDIFF_CONNECTION_STRING -t -c "select tablename from pg_tables where schemaname not in ('information_schema', 'pg_catalog')" $db | awk 'NF {print($1)}')
 
 for table in $tables
 do
@@ -22,7 +28,7 @@ do
     # create a directory for the second capture
     mkdir -p "$secondpath"
 
-    cpy=$(psql -c "copy $table to STDOUT WITH CSV HEADER" $db)
+    cpy=$(psql $PGDIFF_CONNECTION_STRING -c "copy $table to STDOUT WITH CSV HEADER" $db)
 
     # save the data to temp file
     echo "$cpy" | sed 1,1d > "$secondpath/$table"
@@ -37,14 +43,14 @@ do
       printf '─%.0s' $(seq ${#table})
       echo ""
       script -q /dev/null \
-          git diff -U0 \
+          git --no-pager diff -U0 \
                    --color-words=. \
                    --no-index -- "$firstpath/$table" "$secondpath/$table" \
                    < /dev/null | \
           tail -n +6 | \
           awk -v headers=$headers 'NR==1{print headers} {print $0"\n"}' | \
           sed 's/,,/, ,/g;s/,,/, ,/g' | \
-          column -t -s,
+          awk -vOFS='\t' -vFS="," 'NF > 0 { $1 = $1 } 1'
     fi
   else
     # a diff has not been captured for the given $id yet
@@ -53,7 +59,7 @@ do
     # create a directory for the first capture
     mkdir -p "$firstpath"
 
-    cpy=$(psql -c "copy $table to STDOUT WITH CSV HEADER" $db)
+    cpy=$(psql $PGDIFF_CONNECTION_STRING -c "copy $table to STDOUT WITH CSV HEADER" $db)
 
     # save the data to temp file
     echo "$cpy" | sed 1,1d > "$firstpath/$table"
